engineStrict: true
strictPeerDependencies: true
verifyDepsBeforeRun: install
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true

packageConfigs:
  svelte-drawer-sheet:
    saveExact: true

allowBuilds:
  esbuild: true
